=== Mouhamed321/TP_InterOp/TP1/Enseignants/enseignants.dtd
<!ELEMENT enseignants ( enseignant, annee? )* >
<!ELEMENT enseignant ( nom, prenom, prenom?, age?) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT prenom (#PCDATA) >
<!ELEMENT age (#PCDATA) >
<!ELEMENT annee (#PCDATA) >
<!ATTLIST enseignant dep CDATA #REQUIRED>
<!ATTLIST enseignants annee CDATA #IMPLIED>
<!ENTITY isis "ISIS">

=== Mouhamed321/TP_InterOp/TP1/Enseignants/enseignants.xml
<!DOCTYPE enseignants SYSTEM "enseignants.dtd">

<enseignants>
    <enseignant dep="&isis;">
        <nom> Singer </nom>
        <prenom> Nicolas </prenom>
        <prenom>Sylvain</prenom>
    </enseignant>
    <enseignant dep="&isis;">
        <nom> Trouilhet </nom>
        <prenom> Sylvie </prenom>
        <age> 38 </age>
    </enseignant>
</enseignants>
